### ISSUE TITLE
[Study]몽고디비 스터디

### ISSUE THREAD

**Issue by kimseyoon** [DongHyunKims/jinniecast#1]
[내용]
몽고디비 스터디 및 지니캐스트 DB설계

[일정]
4/19 ~4/20

[소요시간]
2day

**Comment by kimseyoon** [comment]
4/19

몽고 디비 스터디(db설치, 기본 데이터 구조 이해, collection, documnet 생성 및 제거, document query 조회)

**Comment by DongHyunKims** [comment]
4/20

mongoDB tutorial 공부
- https://github.com/DongHyunKims/mysql-notes/tree/master/notes/mongoDB

**Comment by kimseyoon** [comment]
스터디완료하여 종료합니다.
