### ISSUE TITLE
[PlayController] 재생목록에 한곡만 있을 경우 다음곡 재생 버튼을 누를 경우

### ISSUE THREAD

**Issue by kimseyoon** [DongHyunKims/jinniecast#110]
[설명]
재생목록에 한곡만 있을 경우  컨트롤러의 다음곡 재생 버튼을 누르면 재생 버튼만 변하고 그대로 재생
큐비디오의 경우 위와 같은 상황에서 다시 재생됨

**Comment by DongHyunKims** [comment]
확인 했습니다 내일 수정 하겠습니다.

**Comment by kimseyoon** [comment]
해당이슈가 해결되어 종료합니다
