### ISSUE TITLE
[MainList] album addBtn 누를 경우 add버튼으로 선택된 객체 배열 서버에 넘겨서 몽고디비에 저장하기

### ISSUE THREAD

**Issue by kimseyoon** [DongHyunKims/jinniecast#56]
[기능]
album addBtn 누를 경우 add버튼으로 선택된 객체 배열 서버에 넘겨서 몽고디비에 저장하기

[소요시간]
2hour

[요구조건]
- [x] 1. album addBtn 누를 경우 add버튼으로 선택된 객체 배열를 ajax로 서버에 잘넘겨지는지 확인
- [x] 2. 서버에서 몽고디비로 잘 저장 되는지 확인
- [x] 3. 다시 클라이언트에서 서버에 잘저장되었는지 확인

**Comment by DongHyunKims** [comment]
searchList 중 검색 후 추가할 동영상을 add 클릭후 추가하지 않고 다른 검색어로 검색해도 추가를 할수 있는 메뉴가 제공되는 문제가 있습니다.

**Comment by kimseyoon** [comment]
문제확인하였습니다.
해당 이슈를 재등록하였습니다.
참고부탁드립니다.
https://github.com/DongHyunKims/jinniecast/issues/66

**Comment by kimseyoon** [comment]
문제를 해결하여 해당이슈를 종료합니다
