### ISSUE TITLE
Learn React 

### ISSUE THREAD

**Issue by sujinleeme** [DongHyunKims/jinniecast#7]
# Online Course
* [Start Using React to Build Web Applications](https://egghead.io/courses/react-fundamentals) 
* codecademy - [Learn ReactJS: Part I](https://www.codecademy.com/learn/react-101), [Learn ReactJS: Part II](https://www.codecademy.com/learn/react-102)

###### etc.
https://egghead.io/technologies/react

**Comment by crongro** [comment]
egghead 가 역시 짱.

**Comment by sujinleeme** [comment]
수강 완료로 이슈 닫겠습니다.
